version: "3"
tasks:
  install:
    cmds:
      - go install honnef.co/go/tools/cmd/staticcheck@latest

  lint:
    cmds:
      - go vet ./...
      - staticcheck ./...

  test:
    deps:
      - lint
    cmds:
      - go test -v ./... {{.CLI_ARGS}}

  generate:
    cmds:
      - go generate ./...