version: "3"
tasks:
  install:
    cmds:
      - go install honnef.co/go/tools/cmd/staticcheck@latest
      - go install go.uber.org/mock/mockgen@latest

  lint:
    cmds:
      - go vet ./...
      - staticcheck ./...

  test:
    deps:
      - lint
    cmds:
      - go test -v ./... {{.CLI_ARGS}}

  test:nocache:
    deps:
      - lint
    cmds:
      - go test -v -count=1 ./... {{.CLI_ARGS}}

  generate:
    cmds:
      - go generate ./...